model: ftransformer
patience: 50 # For early stopping. How many epochs to wait.
epochs: 100 # number of epochs
b_sz: 512 # batch size
is_valid : 0
report_test: 0
inference_mode: False # If train mode, set as False, for test mode, set as True
train_path: /media/6TB_Volume/DataRepo/LargeSyntheticData/train # can be a directory or a file
valid_path: /media/6TB_Volume/DataRepo/LargeSyntheticData/valid # can be a directory or a file
test_path: /media/6TB_Volume/DataRepo/LargeSyntheticData/test # can be a directory or a file
extension: parquet # data type extension, supports   csv and parquet (parquet yet to be implemented)
n_classes: 2 # number of classes
ckpt_path: None # if you want to load the model from a specific checkpoint, supply the path to the checkpoint file
num_feat_path: /media/6TB_Volume/DataRepo/LargeSyntheticData/numerical_clms.csv # a csv file containing the required features
# categ_feat_path: /home/vineeth/Documents/GitWorkSpace/PytorchRecipes/SimpleMLP/Dataset/defaultCredit/categorical_clms.csv # a csv file containing the required features
label_clm: label
model_storage_path: /home/vineeth/Documents/GitWorkSpace/PytorchRecipes/SimpleMLP/trained_weights